# app/Dockerfile.portal
FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código
COPY . .

# Exponer el puerto 8502 (Específico para el portal)
EXPOSE 8502

# Ejecutar Streamlit en el puerto 8502
CMD ["streamlit", "run", "portal_cliente.py", "--server.port=8502", "--server.address=0.0.0.0"]